app/login/forms.py
#!flask/bin/python
# encoding: utf-8
# coding:utf-8

from wtforms.validators import DataRequired, Length, Email, EqualTo, Regexp
from flask.ext.wtf import Form
from wtforms import PasswordField, StringField
from ..models import User
from wtforms import ValidationError


class PasswordResetRequestForm(Form):
    email = StringField('Email',
                        validators=[DataRequired(message=u'不输入邮箱就到不了下一步哦'), Length(1, 128), Email(message=u'邮箱格式好像不对')])

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first() is None:
            raise ValidationError(u'邮箱没注册')


class PasswordResetForm(Form):
    email = StringField('Email', validators=[DataRequired(message=u'没有邮箱我们不知道你谁哦'), Length(1, 128),
                                             Email(message=u'邮箱格式好像不对')])
    password = PasswordField('New Password', validators=[
        DataRequired(message=u'改密码怎么能不写密码呢'), EqualTo('password2', message=u'密码必须一致')])
    password2 = PasswordField('Confirm password', validators=[DataRequired()])

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first() is None:
            raise ValidationError(u'邮箱没注册')


class LoginForm(Form):
    email = StringField(u'邮箱', validators=[DataRequired(message=u'邮箱都不写怎么登陆'), Length(1, 128), Email(message=u'格式不对哦')])
    password = PasswordField(u'密码', validators=[DataRequired(message=u'请输入密码')])

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first() is None:
            raise ValidationError(u'邮箱没注册')


class ChangePasswordForm(Form):
    old_password = PasswordField('Old password', validators=[DataRequired(message=u'是不是忘了密码了')])
    password = PasswordField('New password', validators=[
        DataRequired(message=u'新密码一定要输的'), EqualTo('password2', message='密码不一致')])
    password2 = PasswordField('Confirm new password', validators=[DataRequired()])


class ChangeEmailForm(Form):
    old_email = StringField('Old Email', validators=[DataRequired(message=u'不写邮箱怎么改'), Length(1, 128),
                                                     Email(message=u'邮箱格式错啦!!')])
    new_email = StringField('New Email', validators=[DataRequired(message=u'新邮箱要输的'), Length(1, 128),
                                                     Email(message=u'邮箱格式错啦!!')])
    password = PasswordField('password', validators=[DataRequired(message=u'请输入密码验证')])

    def validate_old_email(self, field):
        if User.query.filter_by(email=field.data).first() is None:
            raise ValidationError(u'邮箱没注册')


class ChangeNameForm(Form):
    name = StringField('Name', validators=[
        DataRequired(message=u'新名字必须输入'), Length(1, 20, message=u'必须是1到20位'),
        Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0, message=u'必须是以英文字母开头的1到64位只含字母和数字的字符串')])
    password = PasswordField('Password', validators=[DataRequired(message=u'密码忘输啦!!')])

    def validate_name(self, field):
        if User.query.filter_by(name=field.data):
            raise ValidationError(u'该用户名已经存在')

app/login/__init__.py
#!flask/bin/python
# encoding: utf-8
from flask import Blueprint


login = Blueprint('login', __name__)


from . import views

app/login/views.py
#!flask/bin/python
# encoding: utf-8
from flask import render_template, redirect, request, url_for, flash, current_app
from flask.ext.login import login_user, logout_user, login_required
from . import login
from ..models import User
from .forms import *
from flask.ext.login import current_user
from ..register.views import send_email
from .. import db


# @login.before_app_request
# def before_request():
#     if current_user.is_authenticated:
#         if not current_user.confirmed \
#                 and request.endpoint[:5] != 'login.' \
#                 and request.endpoint != 'static':
#             return redirect(url_for('login.unconfirmed'))
#
#
# @login.route('/unconfirmed')
# def unconfirmed():
#     if current_user.is_anonymous or current_user.confirmed:
#         return redirect(url_for('login.user_login'))
#     return render_template('login/unconfirmed.html')


@login.route('/', methods=['GET', 'POST'])
def user_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None and user.verify_password(form.password.data):
            login_user(user)
            if not user.confirmed:
                email_url = 'http://mail.' + form.email.data.split('@', 1)[-1]
                return render_template('login/unconfirmed.html', user=user, email_url=email_url)
            if user.identity == 'par':
                return redirect(url_for('participant.homepage'))
            else:
                return redirect(url_for('hosts.index'))
        flash(u'检查一下是不是邮箱或者密码输错了')
    return render_template('login/user_login.html', form=form)


@login.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.')
    return redirect(url_for('login.user_login'))


@login.route('/reset', methods=['GET', 'POST'])
def password_reset_request():
    form = PasswordResetRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            token = user.generate_reset_password_token()
            try:
                send_email(user.email, 'Reset Your Password',
                           'login/email/change_password',
                           user=user, token=token)
                flash('An email with instructions to reset your password has been '
                      'sent to you.')
                return redirect(url_for('login.user_login'))
            except:
                flash('Email sending fail')
    return render_template('login/reset_password_request.html', form=form)


@login.route('/reset/<token>', methods=['GET', 'POST'])
def password_reset(token):
    form = PasswordResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None:
            flash('the email is not registered')
            return redirect(url_for('login.user_login'))
        if user.reset_password(token, form.password.data):
            flash('Your password has been updated.')
            return redirect(url_for('login.user_login'))
        else:
            flash('unsuccessful')
            return redirect(url_for('login.user_login'))
    return render_template('login/reset_password.html', form=form)


@login.route('/change-password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.old_password.data):
            current_user.password = form.password.data
            db.session.add(current_user)
            flash('Your password has been updated.')
            # if current_user.identity == 'par':
            #     return redirect(url_for('participant.homepage'))
            # else:
            #     return redirect(url_for('hosts.index'))
            return redirect(url_for('login.user_login'))
        else:
            flash('Invalid password.')
    return render_template("login/change_password.html", form=form)


@login.route('/change-email', methods=['GET', 'POST'])
@login_required
def change_email_request():
    form = ChangeEmailForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.password.data):
            new_email = form.new_email.data
            token = current_user.generate_change_email_token(new_email)
            try:
                send_email(form.old_email.data, 'Confirm your email address',
                           'login/email/change_email',
                           user=current_user, token=token)
                flash('An email with instructions to reset your password has been '
                      'sent to you.')
                return redirect(url_for('login.user_login'))
            except:
                flash('Email sending failed')
    return render_template("login/change_email.html", form=form)


@login.route('/change-email/<token>')
@login_required
def change_email(token):
    if current_user.change_email(token):
        flash('Your email address has been updated.')
    else:
        flash('Invalid request.')
    if current_user.identity == 'par':
        return redirect(url_for('participant.homepage'))
    else:
        return redirect(url_for('hosts.index'))


@login.route('/change-name', methods=['GET', 'POST'])
@login_required
def change_name():
    form = ChangeNameForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.password.data):
            new_name = form.name.data
            if current_user.change_name(new_name):
                flash('Your name has been update.')
            else:
                flash('Invalid request.')
    return render_template("login/change_name.html", form=form)

app/templates/login/change_email.html
{% extends "base.html" %}

{% block title %}更改电子邮箱地址{% endblock %}

{% block page_content %}
    <div class="login-page">
        <div class="row">
            <div class="col-xs-6 col-md-4 col-lg-offset-4">
                <h3 class="text-center">输入旧电子邮件地址和新地址</h3>
                <br>
                <form class="form-horizontal" role="form" method="post"
                      action="{{ url_for('login.change_email_request') }}">
                    {{ form.csrf_token }}
                    <div class="form-group form-group-lg">
                        <div class="col-sm-offset-1 col-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><span style="font-size: 20px">@</span> </span>
                                {{ form.old_email(class='form-control', placeholder='旧地址') }}
                            </div>
                            {% for errors in form.old_email.errors %}
                                <span class="col-sm-12" style="color: #ff0000; text-align: center;">{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-group form-group-lg">
                        <div class="col-sm-offset-1 col-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><span style="font-size: 20px">@</span> </span>
                                {{ form.new_email(class='form_control', placeholder='新地址') }}
                            </div>
                            {% for error in form.new_email.errors %}
                                <span class="col-sm-12" style="color: #ff0000; text-align: center;">{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-group form-group-lg">
                        <div class="col-sm-offset-1 col-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span> </span>
                                {{ form.password(class='form_control', placeholder='密码') }}
                            </div>
                            {% for error in form.password.errors %}
                                <span class="col-sm-12" style="color: #ff0000; text-align: center;">{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-group form-group-lg">
                        <div class="col-sm-offset-4 col-sm-5">
                            <button type="submit" class="btn btn-success btn-block btn-lg">确定</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/login/change_name.html
{% extends "base.html" %}

{% block title %}更改用户名{% endblock %}

{% block page_content %}
<div class="login-page">
<div class="row"></div>
    <div class="col-xs-6 col-md-4 col-xs-offset-4">
        <h3 class="text-center">输入新的用户名和密码</h3>
        <br>
        <form class="form-horizontal" role="form" method="post" action="{{ url_for('login.change_name') }}">
            <div class="form-group form-group-lg">
                <div class="col-sm-offset-1 col-sm-10">
                    <div class="input-group">
                        <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span> </span>
                        {{ form.name(class='form-control', placeholder='新用户名') }}
                    </div>
                    {% for error in form.name.errors %}
                        <span class="col-sm-12" style="color: #ff0000; text-align: center;">{{ error }}</span>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group form-group-lg">
                <div class="col-sm-offset-1 col-sm-10">
                    <div class="input-group">
                        <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span> </span>
                        {{ form.password(class='form-control', placeholder='密码') }}
                    </div>
                    {% for error in form.name.errors %}
                        <span class="col-sm-12" style="color: #ff0000; text-align: center;">{{ error }}</span>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group form-group-lg">
                <div class="col-sm-offset-4 col-sm-5">
                    <button type="submit" class="btn btn-success btn-block btn-lg">确定</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/templates/login/change_password.html
{% extends "base.html" %}

{% block title %}改密码{% endblock %}

{% block page_content %}
    <div class="login-page">
        <div class="row">
            <div class="col-xs-6 col-md-4 col-sm-offset-4">
                <h3 class="text-center">输入旧密码和新密码</h3>
                <br>
                <form class="form-horizontal" role="form" method="post" action="{{ url_for('login.change_password') }}">
                    {{ form.csrf_token }}
                    <div class="form-group form-group-lg">
                        <div class="col-sm-offset-1 col-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span> </span>
                                {{ form.old_password(class='form-control', placeholder='旧密码') }}
                            </div>
                            {% for error in form.old_password.errors %}
                                <span class="col-sm-12" style="color: #ff0000; text-align: center;">{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-group form-group-lg">
                        <div class="col-sm-offset-1 col-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span> </span>
                                {{ form.password(class='form-control', placeholder='新密码') }}
                            </div>
                            {% for error in form.password.errors %}
                                <span class="col-sm-12" style="color: #ff0000; text-align: center;">{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-group form-group-lg">
                        <div class="col-sm-offset-1 col-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span> </span>
                                {{ form.password2(class='form-control', placeholder='新密码') }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group form-group-lg">
                        <div class="col-sm-offset-4 col-sm-5">
                            <button type="submit" class="btn btn-success btn-block btn-lg">确定</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/login/reset_password.html
{% extends "base.html" %}

{% block title %}
    重置密码
{% endblock %}

{% block page_content %}
    <div class="login-page">
        <div class="col-xs-6 col-md-4 col-lg-offset-4">
            <h3 class="text-center">输入新密码</h3>
            <br>
            <form class="form-horizontal" role="form" method="post">
                {{ form.csrf_token }}
                <div class="form-group form-group-lg">
                    <div class="col-sm-offset-1 col-sm-10">
                        <div class="input-group">
                            <span class="input-group-addon"><span style="font-size: 20px">@</span> </span>
                            {{ form.email(class='form-control', placeholder='电子邮件') }}
                        </div>
                        {% for error in form.email.errors %}
                            <span class="col-sm-12" style="color: #ff0000; text-align: center;">{{ error }}</span>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-group form-group-lg">
                    <div class="col-sm-offset-1 col-sm-10">
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span> </span>
                            {{ form.password(class='form-control', placeholder='密码') }}
                        </div>
                        {% for error in form.password.errors %}
                            <span class="col-sm-12" style="color: #ff0000; text-align: center;">{{ error }}</span>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-group form-group-lg">
                    <div class="col-sm-offset-1 col-sm-10">
                        <div class="input-group">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span> </span>
                            {{ form.password2(class='form-control', placeholder='再次输入密码') }}
                        </div>
                    </div>
                </div>
                <div class="form-group form-group-lg">
                    <div class="col-sm-offset-4 col-sm-5">
                        <button type="submit" class="btn btn-success btn-block btn-lg">确定</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

app/templates/login/reset_password_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>confirm</title>
</head>
<body>
<a href="{{ url_for('login.password_reset', user_id=user_id, token=token, _external=True) }}">confirm</a>
</body>
</html>

app/templates/login/reset_password_request.html
{% extends 'base.html' %}

{% block title %}
    重置密码
{% endblock %}

{% block page_content %}
    <div class="reset_password_request">
        <div class="row">
            <div class="col-xs-6 col-md-5 col-lg-offset-4">
                <h3 class="text-center">请输入注册时用的邮箱</h3>
                <br>
                <form class="form-horizontal" role="form" method="post" action="{{ url_for('login.password_reset_request') }}">
                    {{ form.csrf_token }}
                    <div class="form-group form-group-lg">
                        <div class="col-sm-offset-1 col-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><span style="font-size: 20px">@</span> </span>
                                {{ form.email(class='form-control', placeholder='电子邮件') }}
                            </div>
                            {% for error in form.email.errors %}
                                <span class="col-sm-12" style="color: #ff0000; text-align: center;">{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-group form-group-lg">
                        <div class="col-sm-offset-4 col-sm-5">
                            <button type="submit" class="btn btn-success btn-block btn-lg">确定</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/login/unconfirmed.html
{% extends "base.html" %}

{% block title %}请认证你的账户{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>
        你好，{{ user.name }}!
    </h1>
    <h3>你的账号好像没有经过邮箱认证。</h3>
    <p>
        在你进入个人主页之前，请检查自己的<a href="{{ email_url }}">邮箱</a>，你会收到带有认证链接的邮件。
    </p>
    <p>
        如果你没有收到邮件<br>
        <a href="{{ url_for('register.resend_confirmation') }}">请单击此处</a>
    </p>
</div>
{% endblock %}

app/templates/login/user_login.html
{% extends "base.html" %}

{% block title %}
    登录
{% endblock %}


{% block page_content %}
    <div class="login-page">
        <div class="row">
            <div class="col-xs-6 col-md-4 col-lg-offset-4">
                <h3 class="text-center">欢迎登录日志管理系统</h3>
                <br>
                <form class="form-horizontal" role="form" method="post" action="{{ url_for('login.user_login') }}">
                    {{ form.csrf_token }}
                    <div class="form-group form-group-lg">
                        <div class="col-sm-offset-1 col-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><span style="font-size: 20px">@</span> </span>
                                {{ form.email(class='form-control', placeholder='电子邮件') }}
                            </div>
                            {% for error in form.email.errors %}
                                <span class="col-sm-12" style="color: #ff0000; text-align: center;">{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-group form-group-lg">
                        <div class="col-sm-offset-1 col-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span> </span>
                                {{ form.password(class='form-control', placeholder='密码') }}
                            </div>
                            {% for error in form.password.errors %}
                                <span class="col-sm-12" style="color: #ff0000; text-align: center;">{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-group">
                        <a class="col-sm-offset-9" href="{{ url_for('login.password_reset_request') }}">忘记密码?</a>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-1 col-sm-5">
                            <button type="submit" class="btn btn-success btn-block btn-lg">登录</button>
                        </div>
                        <div class="col-sm-5">
                            <button type="button" class="btn btn-primary btn-block btn-lg"
                                    onclick="{location.href= '/user_register'}">注册
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}