app/participant/forms.py
#!flask/bin/python
# encoding: utf-8

from flask_wtf import Form
from wtforms import StringField
from wtforms.validators import DataRequired, Length, Regexp


class SearchByHostForm(Form):
    host_name = StringField('host_name', validators=[
        DataRequired(message=u'这里必须填哦'), Length(1, 64, message=u'必须1到64位字符串'),
        Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0, message=u'必须由1到64位以字母开头的数字和字母组成')])


class SearchByActivityForm(Form):
    activity_name = StringField('activity_name', validators=[DataRequired(message=u'这里必须填哦')])


class DeleteActivityForm(Form):
    activity_id = StringField('activity_id', validators=[DataRequired(message=u'这里必须填哦')])


class DeleteActivitiesForm(Form):
    activity_ids = StringField('activity_ids', validators=[DataRequired(message=u'这里必须填哦')])


class AddActivityForm(Form):
    activity_id = StringField('activity_id', validators=[DataRequired(message=u'这里必须填哦')])


class AddActivitiesForm(Form):
    activity_ids = StringField('activity_ids', validators=[DataRequired(message=u'这里必须填哦')])

app/participant/__init__.py
#!flask/bin/python
# encoding: utf-8

from flask import Blueprint

participant = Blueprint('participant', __name__)

from . import views

app/participant/views.py
#!flask/bin/python
# encoding: utf-8
from flask import request, render_template, json, redirect, url_for, g, flash
from flask_login import login_required, current_user
from . import participant
from forms import SearchByActivityForm, SearchByHostForm, DeleteActivityForm, \
    DeleteActivitiesForm, AddActivityForm, AddActivitiesForm
from ..models import User, Bookmark, Activity, get_activities
from .. import db


@participant.before_request
def before_request():
    g.user = current_user


@participant.route('/participant', methods=['GET', 'POST'])
@participant.route('/participant/homepage', methods=['GET', 'POST'])
@participant.route('/participant/homepage/<int:page>', methods=['GET', 'POST'])
@login_required
def homepage(page=1):
    form1 = SearchByHostForm()
    form2 = SearchByActivityForm()
    bookmarks = Bookmark.query.filter_by(owner_id=g.user.id)
    pagination = bookmarks.paginate(page, 2, False)
    activities = get_activities(pagination.items)
    return render_template('participant/homepage.html', activities=activities,
                           form1=form1, form2=form2, pagination=pagination,
                           endpoint='participant.homepage', page=page)


@participant.route('/participant/activity_details/<activity_id>')
@login_required
def activity_details(activity_id):
    activity = Activity.query.get_or_404(int(activity_id))
    activity.update_flag = False
    host = User.query.filter_by(id=activity.host_id).first()
    schedules = activity.schedules
    return render_template('activity_details.html',
                           activity=activity, host=host, schedules=schedules, identity='participant')


@participant.route('/participant/search_host', methods=['GET', 'POST'])
@login_required
def search_host():
    method = 'host'
    form = SearchByHostForm()
    if form.validate_on_submit():
        return redirect(url_for('participant.search_result', method=method, query=form.host_name.data))
    return redirect(url_for('participant.homepage'))


@participant.route('/participant/search_activity', methods=['GET', 'POST'])
@login_required
def search_activity():
    method = 'activity'
    form = SearchByActivityForm()
    if form.validate_on_submit():
        return redirect(url_for('participant.search_result', method=method, query=form.activity_name.data))
    return redirect(url_for('participant.homepage'))


@participant.route('/participant/search_result/<method>/<query>', methods=['GET', 'POST'])
@participant.route('/participant/search_result/<method>/<query>/<int:page>', methods=['GET', 'POST'])
@login_required
def search_result(method, query, page=1):
    activities = None
    if method == 'host':
        host_id = User.query.filter_by(name=query).first().id
        activities = Activity.query.filter_by(host_id=host_id).order_by(Activity.start_date.desc())
        if activities is None:
            flash(u'未找到相关主办方的活动')
            return redirect(url_for('participant.homepage'))
    if method == 'activity':
        activities = Activity.query.filter(Activity.name.like('%' + query + '%')).order_by(
            Activity.start_date.desc())
        a_list = activities.all()
        if len(a_list) == 0:
            flash(u'没有找到含有该字段的活动')
            return redirect(url_for('participant.homepage'))
    form1 = AddActivityForm()
    form2 = AddActivitiesForm()
    activities_per_page = activities.paginate(page, 2, False)
    return render_template('participant/search_result.html', query=query, activities=activities_per_page, form1=form1,
                           form2=form2, method=method, endpoint='participant.search_result', page=page)


@participant.route('/participant/search_add_activity', methods=['GET', 'POST'])
@login_required
def add_activity():
    form = AddActivityForm()
    method = request.args.get('method', type=unicode)
    query = request.args.get('query', type=unicode)
    if form.validate_on_submit():
        activity_id = int(form.activity_id.data)
        owner_id = g.user.id
        bookmark = Bookmark(owner_id=owner_id, activity_id=activity_id)
        bookmark.add()
        db.session.commit()
        flash(u'活动添加成功')
        return redirect(url_for('participant.search_result', method=method, query=query,
                                page=request.args.get('page', 1, type=int)))
    return redirect(url_for('participant.search_result', method=method, query=query,
                            page=request.args.get('page', 1, type=int)))


@participant.route('/participant/search_add_activities', methods=['GET', 'POST'])
@login_required
def add_activities():
    form = AddActivitiesForm()
    method = request.args.get('method', type=unicode)
    query = request.args.get('query', type=unicode)
    if form.validate_on_submit():
        activity_ids = json.loads(form.activity_ids.data)
        for activity_id in activity_ids:
            activity_id_int = int(activity_id)
            owner_id = g.user.id
            bookmark = Bookmark(owner_id=owner_id, activity_id=activity_id_int)
            bookmark.add()
        db.session.commit()
        flash(u'活动添加成功')
        return redirect(url_for('participant.homepage'))
    if g.method == 'host':
        return redirect(
            url_for('participant.search_result', method=method, query=query,
                    page=request.args.get('page', 1, type=int)))
    if g.method == 'activity':
        return redirect(
            url_for('participant.search_result', method=method, query=query,
                    page=request.args.get('page', 1, type=int)))


@participant.route('/participant/bookmark_manage', methods=['GET', 'POST'])
@login_required
def bookmark_manage():
    form1 = DeleteActivityForm()
    form2 = DeleteActivitiesForm()
    page = request.args.get('page', 1, type=int)
    bookmarks = Bookmark.query.filter_by(owner_id=g.user.id)
    pagination = bookmarks.paginate(page, 2, False)
    activities = get_activities(pagination.items)
    return render_template('participant/manage_bookmark.html', activities=activities, form1=form1,
                           form2=form2, page=page,
                           endpoint='participant.bookmark_manage', pagination=pagination)


@participant.route('/participant/bookmark_manage/delete_activity', methods=['GET', 'POST'])
@login_required
def delete_activity():
    form = DeleteActivityForm()
    if form.validate_on_submit():
        bookmark = Bookmark.query.filter_by(owner_id=g.user.id, activity_id=int(form.activity_id.data)).first()
        db.session.delete(bookmark)
        db.session.commit()
        flash(u'删除成功')
        return redirect(url_for('participant.bookmark_manage', page=request.args.get('page', 1, type=int)))
    return redirect(url_for('participant.bookmark_manage', page=request.args.get('page', 1, type=int)))


@participant.route('/participant/bookmark_manage/delete_activities', methods=['GET', 'POST'])
@login_required
def delete_activities():
    form = DeleteActivitiesForm()
    if form.validate_on_submit():
        activity_ids = json.loads(form.activity_ids.data)
        for item in activity_ids:
            bookmark = Bookmark.query.filter_by(owner_id=g.user.id, activity_id=int(item)).first()
            db.session.delete(bookmark)
        db.session.commit()
        flash(u'成功删除')
        return redirect(url_for('participant.homepage'))
    return redirect(url_for('participant.bookmark_manage', page=request.args.get('page', 1, type=int)))

app/templates/participant/homepage.html
{% extends 'participant/participant_base.html' %}
{% import 'pagination_macro.html' as macro %}

{% block title %}参与者主页{% endblock %}

{% block stylesheet %}
    {{ super() }}
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
{% endblock %}

{% block page_content %}
    <div class="row">
        <div class="col-lg-offset-1 col-lg-7" style="margin-top: 20px;">
            <form class="form-group" role="form" method="post" action="{{ url_for('participant.search_host') }}">
                {{ form1.csrf_token }}
                <div class="input-group">
                    <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span> </span>
                    {{ form1.host_name(class='form-control', placeholder='通过用户名搜索') }}
                    <div class="input-group-btn">
                        <button type="submit" class="btn btn-success">
                            搜索
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-offset-1 col-lg-7" style="margin-top: 10px;">
            <form class="form-group" role="form" method="post" action="{{ url_for('participant.search_activity') }}">
                {{ form2.csrf_token }}
                <div class="input-group">
                    <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span> </span>
                    {{ form2.activity_name(class='form-control', placeholder='通过活动进行搜索') }}
                    <div class="input-group-btn">
                        <button type="submit" class="btn btn-success">
                            搜索
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="body-wrap">
            {% for activity in activities %}
                <article id="post-bookmark-activity" class="article article-type-activities show is-hidden"
                         itemscope itemprop="activitiesPost">
                    <div class="article-meta">
                        <a href="#" class="article-date">
                            {{ activity.start_date.strftime('%m-%d') }}
                        </a>
                    </div>
                    <div class="article-inner">
                        <header class="article-header">
                            <h1 itemprop="name">
                                <a class="article-title"
                                   href="{{ url_for('participant.activity_details', activity_id=activity.id) }}"
                                        {% if activity.update_flag %}
                                   style="color: red;"
                                        {% endif %}>
                                    {{ activity.name }}
                                </a>
                            </h1>
                        </header>
                        <div class="article-entry" itemprop="activityInfo">
                            <p>
                                {{ activity.introduction }}<br>
                            </p>
                        </div>
                    </div>
                    <div class="article-info article-info-index">
                        <div class="clearfix"></div>
                    </div>
                </article>
            {% endfor %}
        </div>
    </div>
    <div class="row">
        <div class="pagination">
            {{ macro.pagination_widget(pagination, endpoint) }}
        </div>
    </div>
{% endblock %}

app/templates/participant/manage_bookmark.html
{% extends 'participant/participant_base.html' %}

{% import 'pagination_macro.html' as macro %}

{% block title %}管理活动{% endblock %}

{% block page_content %}
    <div class="row">
        <div class="entry-box manage-articles">
            <h3><strong>管理收藏夹</strong></h3>
            <hr/>
            <div class="row articles-list">
                <div class="list-handle">
                    <div class="form-group">
                        <div class="col-sm-2">
                            <a class="btn btn-danger" id="deleteActivities">
                                <span class="glyphicon glyphicon-trash"></span>批量删除
                            </a>
                        </div>
                    </div>
                </div>
                <div class="list-details">
                    <form class="delete-activities" id="deleteActivitiesForm" method="post"
                          action="{{ url_for('participant.delete_activities', page=page) }}">
                        {{ form2.csrf_token }}
                        {{ form2.activity_ids(type='hidden', value='') }}
                        <form>
                            {{ form1.activity_id(type='hidden') }}
                        </form>
                        <table class="table table-striped table-hover">
                            <thead>
                            <tr class="table-header">
                                <th class="table-checkbox-or-left"><input type="checkbox" id="select-all">全选</th>
                                <th>活动名称</th>
                                <th>开始日期</th>
                                <th>删除</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for activity in activities %}
                                <tr>
                                    <td class="table-checkbox-or-left"><input type="checkbox" class="op_check"
                                                                              value="{{ activity.id }}"></td>
                                    <td class="table-checkbox-or-left"><a
                                            href="{{ url_for('participant.activity_details', activity_id=activity.id) }}"
                                            target="_blank">
                                        {{ activity.name }}
                                    </a></td>
                                    <td>{{ activity.start_date.strftime('%m-%d') }}</td>
                                    <td>
                                        <form class="delete-activity" id="deleteActivityForm{{ activity.id }}" method="post"
                                              action="{{ url_for('participant.delete_activity', page=page) }}">
                                            {{ form1.csrf_token }}
                                            {{ form1.activity_id(type='hidden', value=activity.id) }}
                                            <a class="btn btn-sm btn-default"
                                               onclick="deleteActivity({{ activity.id }})" title="删除活动">
                                                <span class="glyphicon glyphicon-trash" style="color: red;"></span>
                                            </a>
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </form>
                </div>
                <div class="pagination">
                    {{ macro.pagination_widget(pagination, endpoint) }}
                </div>
            </div>
        </div>
        <div class="modal fade" id="deleteActivityModal">
            <div class="modal-dialog">
                <div class="modal-content message_align">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title">确认删除？</h4>
                    </div>
                    <div class="modal-body">
                        <p>删除之后不可恢复，确认删除吗？</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                        <a id="deleteActivityConfirm" class="btn btn-success" data-dismiss="modal">确定</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="selectActivityModal">
            <div class="modal-dialog">
                <div class="modal-content message_align">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title">未选择活动</h4>
                    </div>
                    <div class="modal-body">
                        <p>请选择要删除的活动</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                        <a class="btn btn-success" data-dismiss="modal">确定</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="deleteActivitiesModal">
            <div class="modal-dialog">
                <div class="modal-content message_align">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title">确认删除所选活动？</h4>
                    </div>
                    <div class="modal-body">
                        <p>删除后不可恢复，确认删除吗？</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                        <a id="deleteActivitiesConfirm" class="btn btn-success" data-dismiss="modal">确定</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/deleteActivity.js') }}"></script>
{% endblock %}

app/templates/participant/participant_base.html
{% extends 'base.html' %}

{% block header %}
    <header style="margin-top: 25px;">
        <div class="header-top">
            <div class="container">
                <h1><a href="{{ url_for('participant.homepage') }}">参与者页面</a> </h1>
            </div>
        </div>
        <nav class="navbar navbar-btn" role="navigation">
            <div class="container">
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class=""><a href="{{ url_for('participant.homepage') }}" style="font-size: 20px;"><span class="glyphicon glyphicon-home" style="font-size: 18px;"></span>主页</a> </li>
                        <li class=""><a href="{{ url_for('participant.bookmark_manage') }}" style="font-size: 20px;">管理收藏夹</a> </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="{{ current_user.gravatar(size=18) }}">
                                {{ current_user.name }}<b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ url_for('login.change_email_request') }}">更改邮箱</a></li>
                                <li><a href="{{ url_for('login.change_password') }}">更改密码</a></li>
                                <li><a href="{{ url_for('login.change_name') }}">更改姓名</a> </li>
                                <li><a href="{{ url_for('login.logout') }}">退出登录</a> </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
{% endblock %}

app/templates/participant/search_result.html
{% extends 'participant/participant_base.html' %}

{% import 'pagination_macro.html' as macro %}

{% block title %}搜索结果{% endblock %}

{% block page_content %}
    <div class="row">
        <div class="entry-box manage-articles">
            <h3><strong>搜索结果</strong></h3>
            <hr/>
            <div class="row articles-list">
                <div class="list-handle">
                    <div class="form-group">
                        <div class="col-sm-2">
                            <a class="btn btn-primary" id="addActivities">
                                <span class="glyphicon glyphicon-plus"></span>批量添加
                            </a>
                        </div>
                    </div>
                </div>
                <div class="list-details">
                    <form class="add-activities" id="addActivitiesForm" method="post"
                          action="{{ url_for('participant.add_activities', page=page, method=method, query=query) }}">
                        {{ form2.csrf_token }}
                        {{ form2.activity_ids(type='hidden', value='') }}
                        <form>
                            {{ form1.activity_id(type='hidden') }}
                        </form>
                        <table class="table table-striped table-hover">
                            <thead>
                            <tr class="table-header">
                                <th class="table-checkbox-or-left"><input type="checkbox" id="select-all">全选</th>
                                <th>活动名称</th>
                                <th>开始日期</th>
                                <th>添加</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for activity in activities.items %}
                                <tr>
                                    <td class="table-checkbox-or-left"><input type="checkbox" class="op_check"
                                                                              value="{{ activity.id }}"></td>
                                    <td class="table-checkbox-or-left"><a
                                            href="{{ url_for('participant.activity_details', activity_id=activity.id) }}"
                                            target="_blank">{{ activity.name }}</a></td>
                                    <td>{{ activity.start_date.strftime('%m-%d') }}</td>
                                    <td>
                                        <form class="add-activity" id="addForm{{ activity.id }}" method="post"
                                              action="{{ url_for('participant.add_activity', page=page, query=query, method=method) }}">
                                            {{ form1.csrf_token }}
                                            {{ form1.activity_id(type='hidden', value=activity.id) }}
                                            <a class="btn btn-primary btn-sm" onclick="addActivity({{ activity.id }})"
                                               title="添加活动">
                                                <span class="glyphicon glyphicon-plus"></span>
                                            </a>
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </form>
                </div>
                <div class="pagination">
                    {{ macro.pagination_widget(activities, endpoint, method=method, query=query) }}
                </div>
            </div>
        </div>
        <div class="modal fade" id="selectActivityFormModal">
            <div class="modal-dialog">
                <div class="modal-content message_align">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title">未选择活动</h4>
                    </div>
                    <div class="modal-body">
                        <p>请选择要添加的活动</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                        <a class="btn btn-success" data-dismiss="modal">确定</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/add.js') }}"></script>
{% endblock %}