app/register/forms.py
#!flask/bin/python
# encoding: utf-8
from flask.ext.wtf import Form
from wtforms import StringField, PasswordField, BooleanField, SubmitField, SelectField
from wtforms.validators import DataRequired, Length, Email, Regexp, EqualTo
from wtforms import ValidationError
from ..models import User


class RegistrationForm(Form):
    email = StringField('Email', validators=[DataRequired(message=u'还没输入邮箱'), Length(1, 128),
                                             Email(message=u'格式不对哦')])
    name = StringField('Name', validators=[
        DataRequired(message=u'这里必须填哦'), Length(1, 64, message=u'必须1到64位字符串'),
        Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0, message=u'必须由1到64位以字母开头的数字和字母组成')])
    password = PasswordField('Password', validators=[
        DataRequired(message=u'密码都不填怎么行'), EqualTo('password2', message=u'密码不一致')])
    password2 = PasswordField('Confirm password', validators=[DataRequired(message=u'这里必须填哦')])
    role = SelectField('Role', choices=[('par', 'Participant'), ('host', 'host')], coerce=str,
                       validators=[DataRequired()])

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError(u'该邮箱已经注册')

    def validate_name(self, field):
        if User.query.filter_by(name=field.data).first():
            raise ValidationError(u'该用户名已存在')

app/register/__init__.py
#!flask/bin/python
# encoding: utf-8
from flask import Blueprint


register = Blueprint('register', __name__)

from . import views

app/register/views.py
#!flask/bin/python
# encoding: utf-8

from app.register import register
from app.register.forms import RegistrationForm
from ..models import User
from flask import redirect, url_for, flash, render_template, Flask, request, current_app
from app import db
from flask.ext.login import current_user
from flask.ext.login import login_required
from threading import Thread
from flask_mail import Message
from app import mail
from flask_login import login_user


def send_async_email(app, msg):
    with app.app_context():
        mail.send(msg)


def send_email(to, subject, template, **kwargs):
    app = current_app._get_current_object()
    msg = Message(app.config['FLASKY_MAIL_SUBJECT_PREFIX'] + subject,
                  sender=app.config['FLASKY_MAIL_SENDER'], recipients=[to])
    msg.body = render_template(template + '.txt', **kwargs)
    msg.html = render_template(template + '.html', **kwargs)
    thr = Thread(target=send_async_email, args=[app, msg])
    thr.start()
    return thr


@register.route('/user_register', methods=['GET', 'POST'])
def user_register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data,
                    name=form.name.data,
                    password=form.password.data,
                    identity=form.role.data)
        db.session.add(user)
        db.session.commit()
        login_user(user)
        email_url = 'http://mail.' + form.email.data.split('@', 1)[-1]
        token = user.generate_confirmation_token()
        try:
            send_email(user.email, 'Confirm Your Account',
                       'register/email/confirm', user=user, token=token)
            flash('A confirmation email has been sent to you by email.')
            return render_template('login/unconfirmed.html', user=user, email_url=email_url)
        except:
            flash('Email sending failed and the  email is wrong')
            return render_template('login/unconfirmed.html', user=user, email_url=email_url)
    return render_template('register/user_register.html', form=form)


@register.route('/confirm/<token>')
@login_required
def confirm(token):
    if current_user.is_anonymous:
        flash(u'请先登录再验证')
        return redirect(url_for('login.user_login'))
    if current_user.confirm(token):
        flash('You have confirmed your account. Thanks!')
    else:
        flash('The confirmation link is invalid or has expired.')
        return redirect(url_for('register.resend_confirmation'))
    if current_user.identity == 'par':
        return redirect(url_for('participant.homepage'))
    else:
        return redirect(url_for('hosts.index'))


@register.route('/confirm')
@login_required
def resend_confirmation():
    token = current_user.generate_confirmation_token()
    if not send_email(current_user, 'register/email/confirm',
                      'Confirm Your Account', user=current_user, token=token):
        flash('Email sending failed')
    else:
        flash('A new confirmation email has been sent to you by email.')
    return redirect(url_for('login.user_login'))

app/templates/register/register_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>confirm</title>
</head>
<body>
<a href="{{ url_for('register.confirm', token=token, _external=True) }}">confirm</a>
</body>
</html>

app/templates/register/user_register.html
{% extends "base.html" %}

{% block title %}注册{% endblock %}

{% block page_content %}
    <div class="login-page">
        <div class="row">
            <div class="col-xs-6 col-md-4 col-lg-offset-4">
                <h3 class="text-center">注册账号</h3>
                <br>
                <form class="form-horizontal" role="form" method="post"
                      action="{{ url_for('register.user_register') }}">
                    {{ form.csrf_token }}
                    <div class="form-group form-group-lg">
                        <div class="col-sm-offset-1 col-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><span style="font-size: 20px">@</span> </span>
                                {{ form.email(class='form-control', placeholder='电子邮件') }}
                            </div>
                            {% for error in form.email.errors %}
                                <span class="col-sm-12" style="color: #ff0000; text-align: center;">{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-group form-group-lg">
                        <div class="col-sm-offset-1 col-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span> </span>
                                {{ form.name(class='form-control', placeholder='用户名') }}
                            </div>
                            {% for error in form.name.errors %}
                                <span class="col-sm-12" style="color: #ff0000; text-align: center">{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-group form-group-lg">
                        <div class="col-sm-offset-1 col-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span> </span>
                                {{ form.password(class='form-control', placeholder='密码') }}
                            </div>
                            {% for error in form.password.errors %}
                                <span class="col-sm-12" style="color: #ff0000; text-align:center;">{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-group form-group-lg">
                        <div class="col-sm-offset-1 col-sm-10">
                            <div class="input-group">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span> </span>
                                {{ form.password2(class='form-control', placeholder='再次输入密码') }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group form-group-lg">
                        <div class="col-sm-offset-1 col-sm-5">
                            <div class="input-group">
                                {{ form.role(class='form-control', placeholder='选择自己的角色') }}
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <button type="submit" class="btn btn-success btn-block btn-lg">注册</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}