app/hosts/forms.py
#!flask/bin/python
# encoding: utf-8

from flask_wtf import Form
from wtforms import StringField, TextAreaField, DateTimeField, DateField
from wtforms.validators import DataRequired, Length, ValidationError


class BigThan(object):
    def __init__(self, fieldname):
        self.fieldname = fieldname

    def __call__(self, form, field):
        other = form[self.fieldname]
        if field.data < other.data:
            raise ValidationError(u'结束时间必须大于开始时间')


class AddActivityForm(Form):
    name = StringField('name', validators=[DataRequired(message=u'必填项'), Length(1, 30, message=u'必须1到15位字符串')])
    start_date = DateField('start_date', validators=[DataRequired(message=u'必填项')])
    end_date = DateField('end_date', validators=[DataRequired(message=u'必填项'), BigThan('start_date')])
    location = StringField('location', validators=[DataRequired(message=u'必填项'), Length(1, 15, message=u'必须1到15位字符串')])
    introduction = TextAreaField('introduction',
                                 validators=[DataRequired(message=u'必填项'), Length(1, 140, message=u'不能超过140字')])


class DeleteActivityForm(Form):
    activity_id = StringField(validators=[DataRequired()])


class DeleteActivitiesForm(Form):
    activity_ids = StringField(validators=[DataRequired()])


class AddScheduleForm(Form):
    start_time = DateTimeField('start_time', format=u'%Y-%m-%d %H:%M', validators=[DataRequired(message=u'必填项')])
    end_time = DateTimeField('end_time', format=u'%Y-%m-%d %H:%M',
                             validators=[DataRequired(message=u'必填项'), BigThan('start_time')])
    location = StringField('location', validators=[DataRequired(message=u'必填项'), Length(1, 30, message=u'不能超过30字符')])
    information = TextAreaField('introduction',
                                validators=[DataRequired(message=u'必填项'), Length(1, 140, message=u'不能超过140字符')])


class DeleteScheduleForm(Form):
    schedule_id = StringField(validators=[DataRequired()])


class DeleteSchedulesForm(Form):
    schedule_ids = StringField(validators=[DataRequired()])


class ActivityScheduleForm(AddScheduleForm):
    act = StringField(validators=[DataRequired()])

app/hosts/__init__.py
#!flask/bin/python
# encoding: utf-8
from flask import Blueprint

hosts = Blueprint('hosts', __name__)

from . import views

app/hosts/views.py
#!flask/bin/python
# encoding: utf-8

from .forms import *
from ..models import Activity, Schedule, User, Bookmark
from flask import flash, redirect, url_for, request, render_template, g, current_app
from flask_login import login_required, current_user
from .. import db
from . import hosts
import json
from ..register.views import send_email


@hosts.before_app_request
def before_request():
    g.activity_id = 0
    g.delete_activities_form = DeleteActivitiesForm()
    g.delete_schedules_form = DeleteSchedulesForm()


@hosts.route('/host/homepage')
@hosts.route('/host/homepage/<int:page>')
def index(page=1):
    activities = Activity.query.filter_by(host_id=current_user.id).order_by(Activity.start_date.desc())
    pagination = activities.paginate(page, 2, False)
    return render_template('host/homepage.html', page=page, pagination=pagination,
                           activities=activities, endpoint='hosts.index')


@hosts.route('/host/add_activity', methods=['GET', 'POST'])
@login_required
def add_activity():
    form = AddActivityForm()
    method = 'add'
    if form.validate_on_submit():
        name = form.name.data
        start_date = form.start_date.data
        end_date = form.end_date.data
        location = form.location.data
        introduction = form.introduction.data
        activity = Activity(name=name, start_date=start_date, end_date=end_date, location=location,
                            introduction=introduction,
                            host_id=current_user.id)
        db.session.add(activity)
        db.session.commit()
        flash('success!')
        return redirect(url_for('hosts.index'))
    return render_template('host/add_activity.html', form=form, method=method)


@hosts.route('/host/edit_activity/<int:activity_id>', methods=['GET', 'POST'])
@login_required
def edit_activity(activity_id):
    activity = Activity.query.get_or_404(activity_id)
    form = AddActivityForm()
    method = 'update'
    if form.validate_on_submit():
        activity.update(form.name.data, form.location.data, form.introduction.data,
                        form.start_date.data, form.end_date.data)
        db.session.add(activity)
        db.session.commit()
        flash(u'活动更新成功')
        return redirect(url_for('hosts.manage_activity', page=request.args.get('page', 1, type=int)))
    form.name.data = activity.name
    form.location.data = activity.location
    form.introduction.data = activity.introduction
    form.start_date.data = activity.start_date
    form.end_date.data = activity.end_date
    return render_template('host/add_activity.html', form=form, method=method)


@hosts.route('/host/manage_activity', methods=['GET', 'POST'])
@login_required
def manage_activity():
    page = request.args.get('page', 1, type=int)
    activities = Activity.query.filter_by(host_id=current_user.id).order_by(Activity.start_date.desc())
    pagination = activities.paginate(page, 3, False)
    form1 = DeleteActivityForm()
    form2 = DeleteActivitiesForm()
    return render_template('host/manage_activity.html', activities=activities, endpoint='hosts.manage_activity',
                           form1=form1, form2=form2, pagination=pagination, page=page)


@hosts.route('/host/delete_activity', methods=['GET', 'POST'])
@login_required
def delete_activity():
    form = DeleteActivityForm()
    if form.validate_on_submit():
        activity_id = int(form.activity_id.data)
        activity = Activity.query.get_or_404(activity_id)
        schedules = Schedule.query.filter_by(activity_id=activity_id)
        bookmarks = Bookmark.query.filter_by(activity_id=activity_id)
        for schedule in schedules:
            db.session.delete(schedule)
        for bookmark in bookmarks:
            participant = User.query.get(bookmark.owner_id)
            try:
                send_email(participant.email, 'Activity Canceled', 'host/email/cancled', user=participant,
                           activity=activity)
            except:
                flash('Email send failed')
            db.session.delete(bookmark)
        db.session.delete(activity)
        db.session.commit()
        flash('success')
        return redirect(url_for('hosts.manage_activity', page=request.args.get('page', 1, type=int)))
    return redirect(url_for('hosts.manage_activity', page=request.args.get('page', 1, type=int)))


@hosts.route('/host/delete_activities', methods=['GET', 'POST'])
@login_required
def delete_activities():
    form = DeleteActivitiesForm()
    if form.validate_on_submit():
        activity_ids = json.loads(form.activity_ids.data)
        for activity_id in activity_ids:
            activity = Activity.query.get_or_404(activity_id)
            schedules = Schedule.query.filter_by(activity_id=activity_id)
            bookmarks = Bookmark.query.filter_by(activity_id=activity_id)
            for schedule in schedules:
                db.session.delete(schedule)
            for bookmark in bookmarks:
                participant = User.query.get(bookmark.owner_id)
                try:
                    send_email(participant.email, 'Activity Canceled', 'host/email/cancled', user=participant,
                               activity=activity)
                except:
                    flash('email send failed')
                db.session.delete(bookmark)
            db.session.delete(activity)
        db.session.commit()
        flash('success')
        return redirect(url_for('hosts.index'))
    return redirect(url_for('hosts.manage_activity', page=request.args.get('page', 1, type=int)))


@hosts.route('/host/add_schedule/<int:activity_id>', methods=['GET', 'POST'])
@login_required
def add_schedule(activity_id):
    form = AddScheduleForm()
    method = 'add'
    page = request.args.get('page', 1, type=int)
    if form.validate_on_submit():
        start_time = form.start_time.data
        end_time = form.end_time.data
        location = form.location.data
        introduction = form.information.data
        activity = Activity.query.get_or_404(activity_id)
        if start_time.date() < activity.start_date or end_time.date() > activity.end_date:
            flash(u'日程的开始日期必须大于活动开始日期, 结束日期必须小于活动结束日期')
            form.start_time.data = None
            return render_template('host/add_schedule.html', form=form, method=method, page=page,
                                   activity_id=activity_id)
        schedule = Schedule(activity_id=activity_id,
                            start_time=start_time, end_time=end_time, location=location, information=introduction)
        db.session.add(schedule)
        db.session.commit()
        flash('success!')
        return redirect(url_for('hosts.manage_activity', page=page))
    return render_template('host/add_schedule.html', form=form, method=method, page=page, activity_id=activity_id)


@hosts.route('/host/edit_schedule/<int:schedule_id>', methods=['GET', 'POST'])
@login_required
def edit_schedule(schedule_id):
    schedule = Schedule.query.get_or_404(schedule_id)
    method = 'update'
    page = request.args.get('page', 1, type=int)
    form = AddScheduleForm()
    activity_id = request.args.get('activity_id', 1, type=int)
    activity = Activity.query.get_or_404(activity_id)
    if form.validate_on_submit():
        if form.start_time.data.date() < activity.start_date or form.end_time.data.date() > activity.end_date:
            flash(u'日程的开始日期必须大于活动开始日期，结束日期必须小于活动结束日期')
            form.start_time.data = None
            return render_template('host/add_schedule.html', form=form, method=method, page=page,
                                   activity_id=activity_id)
        schedule.update(form.information.data, form.location.data,
                        form.start_time.data, form.end_time.data)
        db.session.add(schedule)
        db.session.commit()
        flash(u'更新成功')
        return redirect(
            url_for('hosts.manage_schedule', activity_id=activity_id, page=page))
    form.information.data = schedule.information
    form.location.data = schedule.location
    form.start_time.data = schedule.start_time
    form.end_time.data = schedule.end_time
    return render_template('host/add_schedule.html', form=form, activity_id=activity_id, method=method, page=page, schedule_id=schedule_id)


@hosts.route('/host/manage_schedule/<int:activity_id>', methods=['GET', 'POST'])
@login_required
def manage_schedule(activity_id):
    g.activity_id = activity_id
    page = request.args.get('page', 1, type=int)
    activity = Activity.query.get_or_404(activity_id)
    schedules = activity.schedules
    # schedules = Schedule.query.filter_by(activity_id=activity_id)
    pagination = schedules.paginate(page, 3, False)
    form1 = DeleteScheduleForm()
    form2 = DeleteSchedulesForm()
    return render_template('host/manage_schedule.html', schedules=schedules, endpoint='hosts.manage_schedule',
                           form1=form1, form2=form2, page=page, pagination=pagination, activity=activity)


@hosts.route('/host/delete-schedule', methods=['GET', 'POST'])
@login_required
def delete_schedule():
    form = DeleteScheduleForm()
    if form.validate_on_submit():
        schedule_id = int(form.schedule_id.data)
        schedule = Schedule.query.get_or_404(schedule_id)
        db.session.delete(schedule)
        db.session.commit()
        flash('success')
        return redirect(url_for('hosts.manage_activity', page=request.args.get('page', 1, type=int)))
    return redirect(
        url_for('hosts.manage_schedule', activity_id=g.activity_id, page=request.args.get('page', 1, type=int)))


@hosts.route('/host/delete-schedules', methods=['GET', 'POST'])
@login_required
def delete_schedules():
    form = DeleteSchedulesForm()
    if form.validate_on_submit():
        schedule_ids = json.loads(form.schedule_ids.data)
        for schedule_id in schedule_ids:
            schedule = Schedule.query.get_or_404(int(schedule_id))
            db.session.delete(schedule)
            db.session.commit()

app/templates/host/homepage.html
{% extends 'host/host_base.html' %}
{% import 'pagination_macro.html' as macro %}

{% block title %}主办方主页{% endblock %}

{% block stylesheet %}
    {{ super() }}
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
{% endblock %}

{% block page_content %}
    <div class="row">
        <div class="body-wrap">
            {% for activity in pagination.items %}
                <article id="post-activity" class="article article-type-activity show is-hidden"
                         itemscope itemprop="activityPost">
                    <div class="article-inner">
                        <header class="article-header">
                            <h1 itemprop="name">
                                <a class="article-title"
                                   href="{{ url_for('hosts.activity_detail', activity_id=activity.id) }}">{{ activity.name }}</a>
                            </h1>
                        </header>
                        <div class="article-entry" itemprop="activityInfo">
                            <p>
                                {{ activity.introduction }}<br>
                            </p>
                        </div>
                    </div>
                    <div class="article-info article-info-index">
                        <div class="clearfix"></div>
                    </div>
                </article>
            {% endfor %}

        </div>
    </div>
    <div class="row">
    <div class="pagination">
        {{ macro.pagination_widget(pagination, endpoint) }}
    </div>
    </div>
{% endblock %}

app/templates/host/host_base.html
{% extends 'base.html' %}

{% block header %}
    <header style="margin-top: 25px;">
        <div class="header-top">
            <div class="container">
                <h1><a href="{{ url_for('hosts.index') }}">主办方页面</a></h1>
            </div>
        </div>
        <nav class="navbar navbar-btn" role="navigation">
            <div class="container">
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class=""><a href="{{ url_for('hosts.index') }}" style="font-size: 20px;"><span
                                class="glyphicon glyphicon-home" style="font-size: 18px;"></span>主页</a></li>
                        <li><a href="{{ url_for('hosts.add_activity') }}" style="font-size: 20px;">添加活动</a></li>
                        <li><a href="{{ url_for('hosts.manage_activity') }}" style="font-size: 20px;">管理活动</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="{{ current_user.gravatar(size=18) }}">
                                {{ current_user.name }}<b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ url_for('login.change_email_request') }}">更改邮箱</a></li>
                                <li><a href="{{ url_for('login.change_password') }}">更改密码</a></li>
                                <li><a href="{{ url_for('login.change_name') }}">更改用户名</a></li>
                                <li><a href="{{ url_for('login.logout') }}">退出登录</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
{% endblock %}

app/templates/host/manage_activity.html
{% extends 'host/host_base.html' %}
{% import 'pagination_macro.html' as macro %}

{% block title %}管理活动{% endblock %}

{% block page_content %}
    <div class="row">
        <div class="entry-box manage-articles">
            <h3><strong>管理活动</strong></h3>
            <hr/>
            <div class="row articles-list">
                <div class="list-handle">
                    <div class="form-group">
                        <div class="col-sm-2">
                            <a class="btn btn-danger" id="deleteActivities">
                                <span class="glyphicon glyphicon-trash"></span>批量删除
                            </a>
                        </div>
                    </div>
                </div>
                <div class="list-details">
                    <form class="delete-activities" id="deleteActivitiesForm" method="post"
                          action="{{ url_for('hosts.delete_activities', page=page) }}">
                        {{ form2.csrf_token }}
                        {{ form2.activity_ids(type='hidden', value='') }}
                        <form>
                            {{ form1.activity_id(type='hidden') }}
                        </form>
                        <table class="table table-striped table-hover">
                            <thead>
                            <tr class="table-header">
                                <th class="table-checkbox-or-left"><input type="checkbox" id="select-all">全选</th>
                                <th>活动名称</th>
                                <th>开始日期</th>
                                <th>添加日程</th>
                                <th>管理日程</th>
                                <th>编辑</th>
                                <th>删除</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for activity in pagination.items %}
                                <tr>
                                    <td class="table-checkbox-or-left"><input type="checkbox" class="op_check"
                                                                              value="{{ activity.id }}"></td>
                                    <td class="table-checkbox-or-left"><a
                                            href="{{ url_for('hosts.activity_detail', activity_id=activity.id) }}"
                                            target="_blank">
                                        {{ activity.name }}
                                    </a></td>
                                    <td>{{ activity.start_date.strftime('%m-%d') }}</td>
                                    <td><a href="{{ url_for('hosts.add_schedule', activity_id=activity.id, page=page) }}"
                                           target="_blank">
                                        <span class="glyphicon glyphicon-plus" title="添加日程"></span>
                                    </a></td>
                                    <td><a href="{{ url_for('hosts.manage_schedule', activity_id=activity.id) }}"
                                           target="_blank">
                                        <span class="glyphicon glyphicon-wrench" title="管理日程"></span>
                                    </a></td>
                                    <td><a href="{{ url_for('hosts.edit_activity', activity_id=activity.id, page=page) }}"
                                           target="_blank">
                                        <span class="glyphicon glyphicon-pencil" title="编辑活动"></span>
                                    </a></td>
                                    <td>
                                        <form class="delete-activity" id="deleteActivityForm{{ activity.id }}" method="post"
                                              action="{{ url_for('hosts.delete_activity', page=page) }}">
                                            {{ form1.csrf_token }}
                                            {{ form1.activity_id(type='hidden', value=activity.id) }}
                                            <a class="btn btn-sm btn-default"
                                               onclick="deleteActivity({{ activity.id }})" title="删除活动">
                                                <span class="glyphicon glyphicon-trash" style="color: red;"></span>
                                            </a>
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </form>
                </div>
                <div class="pagination">
                    {{ macro.pagination_widget(pagination, endpoint) }}
                </div>
            </div>
        </div>
        <div class="modal fade" id="deleteActivityModal">
            <div class="modal-dialog">
                <div class="modal-content message_align">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title">确认删除？</h4>
                    </div>
                    <div class="modal-body">
                        <p>删除之后不可恢复，确认删除吗？</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                        <a id="deleteActivityConfirm" class="btn btn-success" data-dismiss="modal">确认</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="selectActivityModal">
            <div class="modal-dialog">
                <div class="modal-content message_align">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title">未选择活动</h4>
                    </div>
                    <div class="modal-body">
                        <p>请选择要删除的活动</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                        <a class="btn btn-success" data-dismiss="modal">确定</a>
                    </div>
                </div>
            </div>
        </div>
    <div class="modal fade" id="deleteActivitiesModal">
        <div class="modal-dialog">
            <div class="modal-content message_align">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">确认删除所选活动？</h4>
                </div>
                <div class="modal-body">
                    <p>删除之后不可恢复，确认删除吗？</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <a id="deleteActivitiesConfirm" class="btn btn-success" data-dismiss="modal">确定</a>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

{% block script %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/deleteActivity.js') }}"></script>
{% endblock %}

app/templates/host/manage_schedule.html
{% extends 'host/host_base.html' %}

{% import 'pagination_macro.html' as macro %}

{% block title %}管理日程{% endblock %}

{% block page_content %}
    <div class="row">
        <div class="entry-box manage-articles">
            <h3><strong>管理日程</strong></h3>
            <hr/>
            <div class="row articles-list">
                <div class="list-handle">
                    <div class="form-group">
                        <div class="col-sm-2">
                            <a class="btn btn-danger" id="deleteSchedules">
                                <span class="glyphicon glyphicon-trash"></span>批量删除
                            </a>
                        </div>
                    </div>
                </div>
                <div class="list-details">
                    <form class="delete-schedules" id="deleteSchedulesForm" method="post"
                          action="{{ url_for('hosts.delete_schedules', page=page) }}">
                        {{ form2.csrf_token }}
                        {{ form2.schedule_ids(type='hidden', value='') }}
                        <form>
                            {{ form1.schedule_id(type='hidden') }}
                        </form>
                        <table class="table table-striped table-hover">
                            <thead>
                            <tr class="table-header">
                                <th class="table-checkbox-or-left"><input type="checkbox" id="select-all">全选</th>
                                <th>地点</th>
                                <th>时间</th>
                                <th>编辑</th>
                                <th>删除</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for schedule in pagination.items %}
                                <tr>
                                    <td class="table-checkbox-or-left"><input type="checkbox" class="op_check"
                                                                              value="{{ schedule.id }}"></td>
                                    <td class="table-checkbox-or-left">{{ schedule.location }}</td>
                                    <td>{{ schedule.start_time.strftime('%m-%d %H:%M') }}</td>
                                    <td>
                                        <a href="{{ url_for('hosts.edit_schedule', page=page, schedule_id=schedule.id, activity_id=activity.id) }}">
                                            <span class="glyphicon glyphicon-pencil" title="编辑日程"></span>
                                        </a>
                                    </td>
                                    <td>
                                        <form class="delete-schedule" id="deleteScheduleForm{{ schedule.id }}" method="post"
                                              action="{{ url_for('hosts.delete_schedule', page=page) }}">
                                            {{ form1.csrf_token }}
                                            {{ form1.schedule_id(type='hidden', value=schedule.id) }}
                                            <a class="btn btn-sm btn-default"
                                               onclick="deleteSchedule({{ schedule.id }})" title="删除活动">
                                                <span class="glyphicon glyphicon-trash" style="color: red;"></span>
                                            </a>
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </form>
                </div>
                <div class="pagination">
                    {{ macro.pagination_widget(pagination, endpoint, activity_id=activity.id) }}
                </div>
            </div>
        </div>
        <div class="modal fade" id="deleteScheduleModal">
            <div class="modal-dialog">
                <div class="modal-content message_align">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title">确认删除？</h4>
                    </div>
                    <div class="modal-body">
                        <p>删除之后不可恢复，确认删除吗？</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                        <a id="deleteScheduleConfirm" class="btn btn-success" data-dismiss="modal">确定</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="selectScheduleModal">
            <div class="modal-dialog">
                <div class="modal-content message_align">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title">未选择活动</h4>
                    </div>
                    <div class="modal-body">
                        <p>请选择要删除的活动</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                        <a class="btn btn-success" data-dismiss="modal">确定</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="deleteSchedulesModal">
            <div class="modal-dialog">
                <div class="modal-content message_align">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>删除后不可恢复，确认删除吗？</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                        <a id="deleteSchedulesConfirm" class="btn btn-success" data-dismiss="modal">确定</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/deleteSchedule.js') }}"></script>
{% endblock %}